# ------------------------------------------------------------------------------
# GitHub Actions CI for CDKTF (Go) project with AWS provider
# Builds and uses a Docker image for all IaC tools and runs all Makefile tests
# ------------------------------------------------------------------------------

name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build CI Docker image
        run: docker build -t vpc-peering-ci .

      - name: Run all Makefile tests in Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            vpc-peering-ci \
            bash -c "
              set -ex
              mkdir -p /workspace/.terraform.d && chown cicd:cicd /workspace/.terraform.d
              mkdir -p /workspace/.npm && chown cicd:cicd /workspace/.npm
              make get
              go mod tidy
              make init
              make gofmt
              make golint
              make sec
              make clean
              make build
              make synth
              make test
            "
